### ISSUE TITLE
VMS does not work with Django 1.9 or 1.8

### ISSUE THREAD

**Issue by maydhak** [systers/vms#178]
While installing VMS on Windows, I installed Django 1.9 since the Guide said the version should be >= 1.6.5. But I ran into problems as syncdb is no longer available in Django 1.9 and its alternate command (migrate) gives an error: 
File "C:\Users\mk\vms\vms\volunteer\views.py", line 6, in <module> from django.core.servers.basehttp
import FileWrapper ImportError: cannot import name FileWrapper. 

Django 1.8 also gave an error using syncdb (failed to create auth_user table which cascaded from some other error).

On a positive note, the installation worked with Django 1.7.

**Comment by smarshy** [comment]
Hi, ran into the exact same problems with 1.9. With 1.8, I could skip over this by running python manage.py migrate auth and then migrate command. However later, it gave the following error while running tests:

django.db.utils.ProgrammingError: relation "auth_user" does not exist

**Comment by willingc** [comment]
Closed by #248 

@tapasweni-pathak @vubo We can open a separate issue for upgrading the Django release.
